"""add foreign key to Review

Revision ID: 579ec9095e86
Revises: ab5131e15ae5
Create Date: 2024-04-03 23:25:16.718586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579ec9095e86'
down_revision = 'ab5131e15ae5'
branch_labels = None
depends_on = None


def upgrade():
    
    # Add foreign key constraint to existing column
    op.create_foreign_key('fk_review_employee_id', 'reviews', 'employees', ['employee_id'], ['id'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
